plugins:
  versa:
    executor: central_deployment_agent
    source: http://github.com/Cloudify-PS/cloudify-versa-plugin/archive/dhcp.zip
    package_name: cloudify-versa-plugin
    package_version: '1.0'

node_types:

  cloudify.versa.nodes.versa_configuration:
    derived_from: cloudify.nodes.Root
    properties:
      versa_config:
        default: {}

  cloudify.versa.nodes.ResourcePool:
    derived_from: cloudify.nodes.Root
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      name:
        default: ""
      ip_address:
        default: ""
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_resource_pool
          inputs: {}
        delete:
          implementation: versa.versa_plugin.operations.delete_resource_pool
          inputs: {}

  cloudify.versa.nodes.CMSLocalOrganization:
    derived_from: cloudify.nodes.Root
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      name:
        default: ""
      networks:
        default: {}
      resources:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_cms_local_organization
          inputs: {}
        delete:
          implementation: versa.versa_plugin.operations.delete_cms_local_organization
          inputs: {}

  cloudify.versa.nodes.Organization:
    derived_from: cloudify.nodes.Root
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      name:
        default: ""
      parent:
        default: ""
      cms_org_name:
        default: ""
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_organization
          inputs: {}
        delete:
          implementation: versa.versa_plugin.operations.delete_organization
          inputs: {}

  cloudify.versa.nodes.Appliance:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      appliance_name:
        default: ""
      management_ip:
        default: ""
      appliance_owner:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_appliance
          inputs: {}
        delete:
          implementation: versa.versa_plugin.operations.delete_appliance
          inputs: {}

  cloudify.versa.nodes.Associated_organization:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      appliance_name:
        default: ""
      organization:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.associate_organization
          inputs: {}

  cloudify.versa.nodes.Router:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      appliance_name:
        default: ""
      org_name:
        default: ""
      name:
        default: ""
      parent_router_name:
        default: ""
      networks:
        default: {}
      routings:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_router
          inputs: {}

  cloudify.versa.nodes.CGNat:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      appliance_name:
        default: ""
      org_name:
        default: ""
      pool:
        default: {}
      rule:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_cgnat
          inputs: {}

  cloudify.versa.nodes.NGFirewall:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      appliance_name:
        default: ""
      org_name:
        default: ""
      policy_name:
        default: ""
      rules:
        default: {}
      url_filtering:
        default: {}
      zones:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_firewall
          inputs: {}
      versa.interfaces.actions:
        add_url_filter:
          implementation: versa.versa_plugin.operations.create_firewall
          inputs:
            url_filters:
              description: list of url filters to apply
              default: {}

  cloudify.versa.nodes.DHCPProfile:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      appliance_name:
        default: ""
      profile_name:
        default: {}
      organizations:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_dhcp_profile
          inputs: {}

  cloudify.versa.nodes.DHCPOptionsProfile:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      appliance_name:
        default: ""
      org_name:
        default: ""
      name:
        default: ""
      domain:
        default: ""
      servers:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_dhcp_options_profile
          inputs: {}

  cloudify.versa.nodes.DHCPLeaseProfile:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      appliance_name:
        default: ""
      org_name:
        default: ""
      lease_profile:
        default: ""
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_dhcp_lease_profile
          inputs: {}

  cloudify.versa.nodes.DHCPGlobalConfiguration:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      appliance_name:
        default: ""
      org_name:
        default: ""
      dhcp_profile:
        default: ""
      lease_profile:
        default: ""
      options_profile:
        default: ""
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_dhcp_global_configuration
          inputs: {}

  cloudify.versa.nodes.DHCPPool:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      appliance_name:
        default: ""
      org_name:
        default: ""
      lease_profile:
        default: ""
      options_profile:
        default: ""
      name:
        default: {}
      mask:
        default: ""
      range_name:
        default: ""
      begin_address:
        default: ""
      end_address:
        default: ""
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_dhcp_pool
          inputs: {}

  cloudify.versa.nodes.DHCPServer:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      appliance_name:
        default: ""
      org_name:
        default: ""
      lease_profile:
        default: ""
      options_profile:
        default: ""
      pool_name:
        default: {}
      name:
        default: ""
      networks:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_dhcp_server
          inputs: {}

  cloudify.versa.nodes.Network:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      appliance_name:
        default: ""
      org_name:
        default: ""
      name:
        default: {}
      interface:
        default: ""
      unit:
        default: ""
      zone:
        default: ""
      router:
        default: ""
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_network
          inputs: {}

  cloudify.versa.nodes.Interface:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      use_existing:
        default: false
      versa_config:
        default: {}
      appliance_name:
        default: ""
      name:
        default: ""
      units:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versa.versa_plugin.operations.create_interface
          inputs: {}


relationships:
    cloudify.versa.pool_connected_to_vm:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.dhcp_profile_connected_to_appliance:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.dhcp_connected_to_routing:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.dhcp_connected_to_organization:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.dhcp_connected_to_profile:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.firewall_connected_to_router:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.firewall_connected_to_org:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.cgnat_connected_to_routing:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.cgnat_connected_to_org:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.router_connected_to_router:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.router_connected_to_org:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.associated:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.parent:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.cms_org_connected_to_pool:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.nms_org_connected_to_cms_org:
      derived_from: cloudify.relationships.connected_to

    cloudify.versa.organization_connected_to_appliance:
      derived_from: cloudify.relationships.connected_to
